// File generated by Antigravity Agent for Firebase project pluster-30fb9
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkqbG9pLsDNm5hHICJ8R6MQw9lSqL9SI',
    appId: '1:124212548321:web:c0ce3192b0a411e3b91da0',
    messagingSenderId: '124212548321',
    projectId: 'pluster-30fb9',
    authDomain: 'pluster-30fb9.firebaseapp.com',
    storageBucket: 'pluster-30fb9.firebasestorage.app',
    measurementId: 'G-CV6YTW58NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluCzvA7EJqDjNtmtrCHQQN-lkxdibnFE',
    appId: '1:124212548321:android:c764a1eccf5e6572b91da0',
    messagingSenderId: '124212548321',
    projectId: 'pluster-30fb9',
    storageBucket: 'pluster-30fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdkqbG9pLsDNm5hHICJ8R6MQw9lSqL9SI',
    appId: '1:124212548321:web:c0ce3192b0a411e3b91da0',
    messagingSenderId: '124212548321',
    projectId: 'pluster-30fb9',
    storageBucket: 'pluster-30fb9.firebasestorage.app',
    iosBundleId: 'com.emreoylumlu.pluster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdkqbG9pLsDNm5hHICJ8R6MQw9lSqL9SI',
    appId: '1:124212548321:web:c0ce3192b0a411e3b91da0',
    messagingSenderId: '124212548321',
    projectId: 'pluster-30fb9',
    storageBucket: 'pluster-30fb9.firebasestorage.app',
    iosBundleId: 'com.emreoylumlu.pluster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkqbG9pLsDNm5hHICJ8R6MQw9lSqL9SI',
    appId: '1:124212548321:web:c0ce3192b0a411e3b91da0',
    messagingSenderId: '124212548321',
    projectId: 'pluster-30fb9',
    authDomain: 'pluster-30fb9.firebaseapp.com',
    storageBucket: 'pluster-30fb9.firebasestorage.app',
    measurementId: 'G-CV6YTW58NZ',
  );
}
