import 'roguelike_models.dart';

class CardPool {
  static const List<CardDefinition> allCards = [
    // ── Kademe 1 — Basic (Temel Kartlar) ──────────────────────
    CardDefinition(
      id: 'card_double_number',
      name: 'Çift Sayı',
      description: 'Spawn slotlarında daha büyük sayı taşı gelme ihtimali artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.spawnWeightBoost,
      effectValue: 1.3,
      iconName: 'hash',
    ),
    CardDefinition(
      id: 'card_energy_saver',
      name: 'Enerji Tasarrufu',
      description: 'Taş yerleştirme enerji maliyeti %15 azalır.',
      tier: CardTier.basic,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.85,
      iconName: 'battery_saver',
    ),
    CardDefinition(
      id: 'card_pulse_boost',
      name: 'Pulse Takviyesi',
      description: 'Taş birleştirmelerinden kazanılan enerji %20 artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.20,
      iconName: 'bolt',
    ),
    CardDefinition(
      id: 'card_combo_starter',
      name: 'Kombo Kıvılcımı',
      description: 'Kombo zinciri bonus skoru %25 artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.25,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_safety_net',
      name: 'Son Soluk (Last Breath)',
      description: 'Ölümcül hamlede 1 defaya mahsus %25 Enerji ile hayata döndürür.',
      tier: CardTier.basic,
      effectType: CardEffectType.minEnergyFloor,
      effectValue: 25.0,
      iconName: 'shield',
    ),
    CardDefinition(
      id: 'card_unlock_multiplier',
      name: 'Çarpan Taşı',
      description: 'Bırakıldığı hücrenin sayı değerini anında x2 yapar.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'multiplier',
      iconName: 'close',
    ),
    CardDefinition(
      id: 'card_unlock_bomb',
      name: 'Bomba Taşı',
      description: 'Artı (+) şeklindeki 5 hücreyi anında patlatır.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'bomb',
      iconName: 'bug_report',
    ),

    // ── Kademe 2 — Mid (Orta Seviye Kartlar) ──────────────────
    CardDefinition(
      id: 'card_unlock_magnet',
      name: 'Mıknatıs Taşı',
      description: 'Aynı sayıları yan yana çekip otomatik birleştirir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'magnet',
      iconName: 'all_inclusive',
    ),
    CardDefinition(
      id: 'card_unlock_prism',
      name: 'Prizma Taşı',
      description: 'Komşu 4 hücrenin sayı değerini +1 yükseltir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'prism',
      iconName: 'style',
    ),
    CardDefinition(
      id: 'card_reactor',
      name: 'Reaktör (Reactor)',
      description: 'Her turun sonunda tahtadaki 1 rastgele hücreye +1 değer ekler.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.25,
      iconName: 'cyclone',
    ),
    CardDefinition(
      id: 'card_chain_master',
      name: 'Zincir Ustası',
      description: 'Kombo zincir bonusu %50 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.50,
      iconName: 'link',
    ),
    CardDefinition(
      id: 'card_overcharge_pulse',
      name: 'Aşırı Yükleme',
      description: 'Kazanılan pulse enerjisi %40 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.40,
      iconName: 'electric_bolt',
    ),
    CardDefinition(
      id: 'card_passive_shield',
      name: 'Koruyucu Şebeke',
      description: 'Taşlaşma lanetini engeller ve enerji kaybını %20 düşürür.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.80,
      iconName: 'security',
    ),
    CardDefinition(
      id: 'card_high_value_spawn',
      name: 'Yüksek Değer Yoğunluğu',
      description: 'Spawn slotlarında yüksek değerli taş gelme şansı %50 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.spawnWeightBoost,
      effectValue: 1.5,
      iconName: 'trending_up',
    ),

    // ── Kademe 3 — Rare (Nadir Seviye Kartlar) ─────────────────
    CardDefinition(
      id: 'card_unlock_wildcard',
      name: 'Joker Taş',
      description: 'Herhangi bir sayı ile anında birleşir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'wildcard',
      iconName: 'star',
    ),
    CardDefinition(
      id: 'card_unlock_nova',
      name: 'Süpernova Taş',
      description: 'Tüm tahtaya +1 Pulse yollayarak zincirleme kombo patlatır.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'nova',
      iconName: 'flare',
    ),
    CardDefinition(
      id: 'card_catalyst',
      name: 'Katalizör (Catalyst)',
      description: 'Değeri 7 olan hücreler otomatik parlar ve her taşla anında patlar.',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.75,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_overflow',
      name: 'Taşma (Overflow)',
      description: 'Birleşmede 10+ değere ulaşan hücreler çifte puan (2x Skor) kazandırır.',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 2.0,
      iconName: 'verified_user',
    ),
    CardDefinition(
      id: 'card_hyper_combo',
      name: 'Hiper Kombo Sinerjisi',
      description: 'Kombo bonusları %100 (2 katı) artar.',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 2.0,
      iconName: 'workspace_premium',
    ),
    CardDefinition(
      id: 'card_unlock_vortex',
      name: 'Girdap Taş',
      description: 'Kilitleri temizler ve tüm taşları merkeze doğru toplar.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'vortex',
      iconName: 'published_with_changes',
    ),
  ];

  static List<CardDefinition> byTier(CardTier tier) =>
      allCards.where((c) => c.tier == tier).toList();

  static CardDefinition byId(String id) =>
      allCards.firstWhere((c) => c.id == id, orElse: () => allCards.first);
}
