import 'roguelike_models.dart';

class CardPool {
  static const List<CardDefinition> allCards = [
    // ── Kademe 1 — Basic (Temel Kartlar) ──────────────────────
    CardDefinition(
      id: 'card_double_number',
      familyId: 'double_number',
      tierLevel: 1,
      name: 'Çift Sayı I',
      description: 'Spawn slotlarında daha büyük sayı taşı gelme ihtimali %30 artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.spawnWeightBoost,
      effectValue: 1.30,
      iconName: 'hash',
    ),
    CardDefinition(
      id: 'card_double_number_t2',
      familyId: 'double_number',
      tierLevel: 2,
      name: 'Çift Sayı II (Yüksek Değer)',
      description: 'Spawn slotlarında daha büyük sayı taşı gelme ihtimali %40 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.spawnWeightBoost,
      effectValue: 1.40,
      iconName: 'hash',
    ),
    CardDefinition(
      id: 'card_double_number_t3',
      familyId: 'double_number',
      tierLevel: 3,
      name: 'Çift Sayı III (Sayı Üstadı)',
      description: 'Spawn slotlarında daha büyük sayı taşı gelme ihtimali %50 artar.',
      tier: CardTier.rare,
      effectType: CardEffectType.spawnWeightBoost,
      effectValue: 1.50,
      iconName: 'hash',
    ),

    CardDefinition(
      id: 'card_energy_saver',
      familyId: 'energy_saver',
      tierLevel: 1,
      name: 'Enerji Tasarrufu I',
      description: 'Taş yerleştirme enerji maliyeti %15 azalır.',
      tier: CardTier.basic,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.85,
      iconName: 'battery_saver',
    ),
    CardDefinition(
      id: 'card_energy_saver_t2',
      familyId: 'energy_saver',
      tierLevel: 2,
      name: 'Enerji Tasarrufu II',
      description: 'Taş yerleştirme enerji maliyeti %25 azalır.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.75,
      iconName: 'battery_saver',
    ),
    CardDefinition(
      id: 'card_energy_saver_t3',
      familyId: 'energy_saver',
      tierLevel: 3,
      name: 'Enerji Tasarrufu III (Süper Şebeke)',
      description: 'Taş yerleştirme enerji maliyeti %35 azalır.',
      tier: CardTier.rare,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.65,
      iconName: 'battery_saver',
    ),

    CardDefinition(
      id: 'card_pulse_boost',
      familyId: 'pulse_boost',
      tierLevel: 1,
      name: 'Pulse Takviyesi I',
      description: 'Taş birleştirmelerinden kazanılan enerji %20 artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.20,
      iconName: 'bolt',
    ),
    CardDefinition(
      id: 'card_pulse_boost_t2',
      familyId: 'pulse_boost',
      tierLevel: 2,
      name: 'Pulse Takviyesi II (Aşırı Yükleme)',
      description: 'Taş birleştirmelerinden kazanılan enerji %30 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.30,
      iconName: 'bolt',
    ),
    CardDefinition(
      id: 'card_pulse_boost_t3',
      familyId: 'pulse_boost',
      tierLevel: 3,
      name: 'Pulse Takviyesi III (Sonsuz Rezonans)',
      description: 'Taş birleştirmelerinden kazanılan enerji %40 artar.',
      tier: CardTier.rare,
      effectType: CardEffectType.energyGainMultiplier,
      effectValue: 1.40,
      iconName: 'bolt',
    ),

    CardDefinition(
      id: 'card_combo_starter',
      familyId: 'combo_starter',
      tierLevel: 1,
      name: 'Kombo Kıvılcımı I',
      description: 'Kombo zinciri bonus skoru %25 artar.',
      tier: CardTier.basic,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.25,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_combo_starter_t2',
      familyId: 'combo_starter',
      tierLevel: 2,
      name: 'Kombo Kıvılcımı II (Zincir Ustası)',
      description: 'Kombo zinciri bonus skoru %35 artar.',
      tier: CardTier.mid,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.35,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_combo_starter_t3',
      familyId: 'combo_starter',
      tierLevel: 3,
      name: 'Kombo Kıvılcımı III (Hiper Kombo)',
      description: 'Kombo zinciri bonus skoru %45 artar.',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.45,
      iconName: 'auto_awesome',
    ),

    CardDefinition(
      id: 'card_safety_net',
      familyId: 'safety_net',
      tierLevel: 1,
      name: 'Son Soluk I',
      description: 'Ölümcül hamlede %25 Enerji ile diriltir.',
      tier: CardTier.basic,
      effectType: CardEffectType.minEnergyFloor,
      effectValue: 25.0,
      iconName: 'shield',
    ),
    CardDefinition(
      id: 'card_safety_net_t2',
      familyId: 'safety_net',
      tierLevel: 2,
      name: 'Son Soluk II (Canlılık Kalkanı)',
      description: 'Ölümcül hamlede %35 Enerji ile diriltir.',
      tier: CardTier.mid,
      effectType: CardEffectType.minEnergyFloor,
      effectValue: 35.0,
      iconName: 'shield',
    ),
    CardDefinition(
      id: 'card_safety_net_t3',
      familyId: 'safety_net',
      tierLevel: 3,
      name: 'Son Soluk III (Ölümsüz Şebeke)',
      description: 'Ölümcül hamlede %45 Enerji ile diriltir.',
      tier: CardTier.rare,
      effectType: CardEffectType.minEnergyFloor,
      effectValue: 45.0,
      iconName: 'shield',
    ),

    CardDefinition(
      id: 'card_passive_shield',
      familyId: 'passive_shield',
      tierLevel: 1,
      name: 'Koruyucu Şebeke I',
      description: 'Taşlaşma lanetini engeller ve enerji kaybını %20 düşürür.',
      tier: CardTier.basic,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.80,
      iconName: 'security',
    ),
    CardDefinition(
      id: 'card_passive_shield_t2',
      familyId: 'passive_shield',
      tierLevel: 2,
      name: 'Koruyucu Şebeke II',
      description: 'Taşlaşma lanetini engeller ve enerji kaybını %30 düşürür.',
      tier: CardTier.mid,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.70,
      iconName: 'security',
    ),
    CardDefinition(
      id: 'card_passive_shield_t3',
      familyId: 'passive_shield',
      tierLevel: 3,
      name: 'Koruyucu Şebeke III',
      description: 'Taşlaşma lanetini engeller ve enerji kaybını %40 düşürür.',
      tier: CardTier.rare,
      effectType: CardEffectType.energyCostMultiplier,
      effectValue: 0.60,
      iconName: 'security',
    ),

    // Special Tile Unlocks
    CardDefinition(
      id: 'card_unlock_multiplier',
      familyId: 'multiplier',
      tierLevel: 1,
      name: 'Çarpan Taşı I',
      description: 'Bırakıldığı hücrenin sayı değerini anında x2 yapar.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'multiplier',
      iconName: 'close',
    ),
    CardDefinition(
      id: 'card_unlock_multiplier_t2',
      familyId: 'multiplier',
      tierLevel: 2,
      name: 'Çarpan Taşı II (Çifte Çarpan)',
      description: 'Bırakıldığı hücrenin sayı değerini anında x2.2 yapar.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'multiplier',
      iconName: 'close',
    ),
    CardDefinition(
      id: 'card_unlock_multiplier_t3',
      familyId: 'multiplier',
      tierLevel: 3,
      name: 'Çarpan Taşı III (Hiper Çarpan)',
      description: 'Bırakıldığı hücrenin sayı değerini anında x2.4 yapar.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'multiplier',
      iconName: 'close',
    ),

    CardDefinition(
      id: 'card_unlock_bomb',
      familyId: 'bomb',
      tierLevel: 1,
      name: 'Bomba Taşı I',
      description: 'Artı (+) şeklindeki 5 hücreyi anında patlatır.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'bomb',
      iconName: 'bug_report',
    ),
    CardDefinition(
      id: 'card_unlock_bomb_t2',
      familyId: 'bomb',
      tierLevel: 2,
      name: 'Bomba Taşı II (Dinamit Taş)',
      description: 'Artı (+) 5 hücreyi patlatır ve +%10 bonus enerji kazandırır.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'bomb',
      iconName: 'bug_report',
    ),
    CardDefinition(
      id: 'card_unlock_bomb_t3',
      familyId: 'bomb',
      tierLevel: 3,
      name: 'Bomba Taşı III (Atomik Bomba)',
      description: 'Artı (+) 5 hücreyi patlatır ve +%20 bonus enerji kazandırır.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'bomb',
      iconName: 'bug_report',
    ),

    CardDefinition(
      id: 'card_unlock_magnet',
      familyId: 'magnet',
      tierLevel: 1,
      name: 'Mıknatıs Taşı I',
      description: 'Aynı sayıları yan yana çekip otomatik birleştirir.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'magnet',
      iconName: 'all_inclusive',
    ),
    CardDefinition(
      id: 'card_unlock_magnet_t2',
      familyId: 'magnet',
      tierLevel: 2,
      name: 'Mıknatıs Taşı II (Süper Mıknatıs)',
      description: 'Aynı sayıları çeker ve bir birleştirmede +%10 skor verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'magnet',
      iconName: 'all_inclusive',
    ),
    CardDefinition(
      id: 'card_unlock_magnet_t3',
      familyId: 'magnet',
      tierLevel: 3,
      name: 'Mıknatıs Taşı III (Kuantum Mıknatıs)',
      description: 'Aynı sayıları çeker ve bir birleştirmede +%20 skor verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'magnet',
      iconName: 'all_inclusive',
    ),

    CardDefinition(
      id: 'card_unlock_prism',
      familyId: 'prism',
      tierLevel: 1,
      name: 'Prizma Taşı I',
      description: 'Komşu 4 hücrenin sayı değerini +1 yükseltir.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'prism',
      iconName: 'style',
    ),
    CardDefinition(
      id: 'card_unlock_prism_t2',
      familyId: 'prism',
      tierLevel: 2,
      name: 'Prizma Taşı II (Çapraz Prizma)',
      description: 'Komşu 4 hücrenin sayı değerini +1 yükseltir ve +%10 skor verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'prism',
      iconName: 'style',
    ),
    CardDefinition(
      id: 'card_unlock_prism_t3',
      familyId: 'prism',
      tierLevel: 3,
      name: 'Prizma Taşı III (Kristal Prizma)',
      description: 'Komşu 4 hücrenin sayı değerini +1 yükseltir ve +%20 skor verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'prism',
      iconName: 'style',
    ),

    CardDefinition(
      id: 'card_unlock_crystal',
      familyId: 'crystal',
      tierLevel: 1,
      name: 'Kristal Taş I',
      description: 'Patladığında fazladan +15 Enerji Kristali verir.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'crystal',
      iconName: 'diamond',
    ),
    CardDefinition(
      id: 'card_unlock_crystal_t2',
      familyId: 'crystal',
      tierLevel: 2,
      name: 'Kristal Taş II (Zengin Kristal)',
      description: 'Patladığında fazladan +20 Enerji Kristali verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'crystal',
      iconName: 'diamond',
    ),
    CardDefinition(
      id: 'card_unlock_crystal_t3',
      familyId: 'crystal',
      tierLevel: 3,
      name: 'Kristal Taş III (Kristal Damarı)',
      description: 'Patladığında fazladan +25 Enerji Kristali verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'crystal',
      iconName: 'diamond',
    ),

    CardDefinition(
      id: 'card_unlock_contagion',
      familyId: 'contagion',
      tierLevel: 1,
      name: 'Bulaşıcı Taş I',
      description: 'Komşu 4 hücreyi kendi değerine dönüştürür.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'contagion',
      iconName: 'coronavirus',
    ),
    CardDefinition(
      id: 'card_unlock_contagion_t2',
      familyId: 'contagion',
      tierLevel: 2,
      name: 'Bulaşıcı Taş II (Virüs Taş)',
      description: 'Komşu 4 hücreyi kendi değerine dönüştürür ve +%10 skor verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'contagion',
      iconName: 'coronavirus',
    ),
    CardDefinition(
      id: 'card_unlock_contagion_t3',
      familyId: 'contagion',
      tierLevel: 3,
      name: 'Bulaşıcı Taş III (Epidemi Taş)',
      description: 'Komşu 4 hücreyi kendi değerine dönüştürür ve +%20 skor verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'contagion',
      iconName: 'coronavirus',
    ),

    CardDefinition(
      id: 'card_unlock_wildcard',
      familyId: 'wildcard',
      tierLevel: 1,
      name: 'Joker Taş I',
      description: 'Herhangi bir sayı ile anında birleşir.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'wildcard',
      iconName: 'star',
    ),
    CardDefinition(
      id: 'card_unlock_wildcard_t2',
      familyId: 'wildcard',
      tierLevel: 2,
      name: 'Joker Taş II (Esnek Joker)',
      description: 'Herhangi bir sayı ile anında birleşir ve +%10 skor verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'wildcard',
      iconName: 'star',
    ),
    CardDefinition(
      id: 'card_unlock_wildcard_t3',
      familyId: 'wildcard',
      tierLevel: 3,
      name: 'Joker Taş III (Kopyalayıcı Joker)',
      description: 'Herhangi bir sayı ile anında birleşir ve +%20 skor verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'wildcard',
      iconName: 'star',
    ),

    CardDefinition(
      id: 'card_unlock_nova',
      familyId: 'nova',
      tierLevel: 1,
      name: 'Süpernova Taş I',
      description: 'Tüm tahtaya +1 Pulse yollayarak zincirleme kombo patlatır.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'nova',
      iconName: 'flare',
    ),
    CardDefinition(
      id: 'card_unlock_nova_t2',
      familyId: 'nova',
      tierLevel: 2,
      name: 'Süpernova Taş II (Güneş Patlaması)',
      description: 'Tüm tahtaya +1 Pulse yollar ve +%10 bonus pulse verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'nova',
      iconName: 'flare',
    ),
    CardDefinition(
      id: 'card_unlock_nova_t3',
      familyId: 'nova',
      tierLevel: 3,
      name: 'Süpernova Taş III (Gala Nova)',
      description: 'Tüm tahtaya +1 Pulse yollar ve +%20 bonus pulse verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'nova',
      iconName: 'flare',
    ),

    CardDefinition(
      id: 'card_unlock_vortex',
      familyId: 'vortex',
      tierLevel: 1,
      name: 'Girdap Taş I',
      description: 'Kilitleri temizler ve tüm taşları merkeze doğru toplar.',
      tier: CardTier.basic,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.0,
      relatedTileType: 'vortex',
      iconName: 'published_with_changes',
    ),
    CardDefinition(
      id: 'card_unlock_vortex_t2',
      familyId: 'vortex',
      tierLevel: 2,
      name: 'Girdap Taş II (Kara Delik)',
      description: 'Kilitleri temizler, taşları toplar ve +%10 skor verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.1,
      relatedTileType: 'vortex',
      iconName: 'published_with_changes',
    ),
    CardDefinition(
      id: 'card_unlock_vortex_t3',
      familyId: 'vortex',
      tierLevel: 3,
      name: 'Girdap Taş III (Singularity)',
      description: 'Kilitleri temizler, taşları toplar ve +%20 skor verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.unlockTileType,
      effectValue: 1.2,
      relatedTileType: 'vortex',
      iconName: 'published_with_changes',
    ),

    CardDefinition(
      id: 'card_catalyst',
      familyId: 'catalyst',
      tierLevel: 1,
      name: 'Katalizör I',
      description: '7 değerli hücreler daha hızlı patlar (%25 Bonus).',
      tier: CardTier.basic,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.25,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_catalyst_t2',
      familyId: 'catalyst',
      tierLevel: 2,
      name: 'Katalizör II',
      description: '7 değerli hücreler daha hızlı patlar (%35 Bonus).',
      tier: CardTier.mid,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.35,
      iconName: 'auto_awesome',
    ),
    CardDefinition(
      id: 'card_catalyst_t3',
      familyId: 'catalyst',
      tierLevel: 3,
      name: 'Katalizör III',
      description: '7 değerli hücreler daha hızlı patlar (%45 Bonus).',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.45,
      iconName: 'auto_awesome',
    ),

    CardDefinition(
      id: 'card_overflow',
      familyId: 'overflow',
      tierLevel: 1,
      name: 'Taşma I (Overflow)',
      description: '10+ değere ulaşan hücre birleşmeleri %25 bonus verir.',
      tier: CardTier.basic,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.25,
      iconName: 'verified_user',
    ),
    CardDefinition(
      id: 'card_overflow_t2',
      familyId: 'overflow',
      tierLevel: 2,
      name: 'Taşma II (Overflow)',
      description: '10+ değere ulaşan hücre birleşmeleri %35 bonus verir.',
      tier: CardTier.mid,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.35,
      iconName: 'verified_user',
    ),
    CardDefinition(
      id: 'card_overflow_t3',
      familyId: 'overflow',
      tierLevel: 3,
      name: 'Taşma III (Overflow)',
      description: '10+ değere ulaşan hücre birleşmeleri %45 bonus verir.',
      tier: CardTier.rare,
      effectType: CardEffectType.comboBonusMultiplier,
      effectValue: 1.45,
      iconName: 'verified_user',
    ),
  ];

  static List<CardDefinition> byTier(CardTier tier) =>
      allCards.where((c) => c.tier == tier).toList();

  static CardDefinition byId(String id) =>
      allCards.firstWhere((c) => c.id == id, orElse: () => allCards.first);
}
